name: Test DBT Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from github to runner
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.13.1

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake